#!/bin/bash

# Define tests to run with --forked
forked_tests=("tests/test_ccxt_interface.py" "tests/test_tickers_manager.py" "tests/test_rpcserver.py" "tests/test_kraken_zinterface.py" "tests/test_kraken_websockets.py")

# Convert forked_tests array to space-separated string for pytest
forked_tests_string="${forked_tests[@]}"

# Run forked tests and save results

#pytest -v -p no:warnings -n 1 --dist=loadscope $forked_tests_string 

# Build pytest ignore arguments for parallel tests
ignore_args=""
for test in "${forked_tests[@]}"; do
  ignore_args+="--ignore=$test "
done

pytest -v -p no:warnings -n 4 --dist=loadscope $ignore_args tests/
